# Generated by Django 5.0.1 on 2025-07-15 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_movie_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
